RK: new RK3328 device, fixed linux version and config

diff --git a/projects/Rockchip/devices/RK3328/options b/projects/Rockchip/devices/RK3328/options
--- a/projects/Rockchip/devices/RK3328/options
+++ b/projects/Rockchip/devices/RK3328/options
@@ -24,13 +24,19 @@
   # Configuration for u-boot
     UBOOT_CONFIG="evb-rk3328_defconfig"
     UBOOT_SOC="rk3328"
-    UBOOT_DTB="rk3328-rock64.dtb"
+    
+  case $BOARD in
+    ROCK64)
+      UBOOT_DTB="rk3328-rock64.dtb"
+      KERNEL_MAKE_EXTRACMD="rockchip/rk3328-rock64.dtb"
+      ;;
+    *)
+      echo "Invalid or missing board $BOARD"
+      exit 1
+    esac
 
   # Kernel target
     KERNEL_TARGET="Image"
-
-  # Additional kernel make parameters (for example to specify the u-boot loadaddress)
-    KERNEL_MAKE_EXTRACMD="rockchip/rk3328-rock64.dtb"
 
   # Mali GPU family
     MALI_FAMILY="450"
