Add Arch Linux Support to create_livestick, thanks to 'egore', this fixes #2647
Signed-off-by: Stephan Raue <stephan@openelec.tv>

diff --git a/packages/tools/syslinux/files/create_livestick b/packages/tools/syslinux/files/create_livestick
--- a/packages/tools/syslinux/files/create_livestick
+++ b/packages/tools/syslinux/files/create_livestick
@@ -258,6 +258,8 @@ EOF
     cp /usr/lib/syslinux/vesamenu.c32 /tmp/usb_install
   elif [ -f /usr/share/syslinux/vesamenu.c32 ]; then
     cp /usr/share/syslinux/vesamenu.c32 /tmp/usb_install
+  elif [ -f /usr/lib/syslinux/bios/vesamenu.c32 ]; then
+    cp /usr/lib/syslinux/bios/vesamenu.c32 /tmp/usb_install
   else
     echo "ERROR: Can't find syslinux's vesamenu.c32 on Host OS" >&2
     sed 's|^UI vesamenu.c32|#UI vesamenu.c32|g' /tmp/usb_install/syslinux.cfg
@@ -267,12 +269,22 @@ EOF
     cp /usr/lib/syslinux/libcom32.c32 /tmp/usb_install
   elif [ -f /usr/share/syslinux/libcom32.c32 ]; then
     cp /usr/share/syslinux/libcom32.c32 /tmp/usb_install
+  elif [ -f /usr/lib/syslinux/bios/libcom32.c32 ]; then
+    cp /usr/lib/syslinux/bios/libcom32.c32 /tmp/usb_install
+  else
+    echo "ERROR: Can't find syslinux's libcom32.c32 on Host OS" >&2
+    exit 1
   fi
 
   if [ -f /usr/lib/syslinux/libutil.c32 ]; then
     cp /usr/lib/syslinux/libutil.c32 /tmp/usb_install
   elif [ -f /usr/share/syslinux/libutil.c32 ]; then
     cp /usr/share/syslinux/libutil.c32 /tmp/usb_install
+  elif [ -f /usr/lib/syslinux/bios/libutil.c32 ]; then
+    cp /usr/lib/syslinux/bios/libutil.c32 /tmp/usb_install
+  else
+    echo "ERROR: Can't find syslinux's libutil.c32 on Host OS" >&2
+    exit 1
   fi
 
 # sync disk
@@ -289,6 +301,8 @@ EOF
     MBR="/usr/lib/syslinux/mbr.bin"       # example: debian, ubuntu
   elif [ -f /usr/share/syslinux/mbr.bin ]; then
     MBR="/usr/share/syslinux/mbr.bin"     # example: fedora
+  elif [ -f /usr/lib/syslinux/bios/mbr.bin ]; then
+    MBR="/usr/lib/syslinux/bios/mbr.bin"  # example: arch
   else
     echo "ERROR: Can't find syslinux's mbr.bin on Host OS" >&2
   fi
