Revert "create_livestick: use our *.c32"
This reverts commit af39048a80480bba689fe96c767b0f523c38c0af.

diff --git a/packages/tools/syslinux/files/create_livestick b/packages/tools/syslinux/files/create_livestick
--- a/packages/tools/syslinux/files/create_livestick
+++ b/packages/tools/syslinux/files/create_livestick
@@ -239,9 +239,26 @@ EOF
 
   cp splash.png /tmp/usb_install
 
-  cp 3rdparty/syslinux/vesamenu.c32 /tmp/usb_install
-  cp 3rdparty/syslinux/libcom32.c32 /tmp/usb_install
-  cp 3rdparty/syslinux/libutil.c32 /tmp/usb_install
+  if [ -f /usr/lib/syslinux/vesamenu.c32 ]; then
+    cp /usr/lib/syslinux/vesamenu.c32 /tmp/usb_install
+  elif [ -f /usr/share/syslinux/vesamenu.c32 ]; then
+    cp /usr/share/syslinux/vesamenu.c32 /tmp/usb_install
+  else
+    echo "ERROR: Can't find syslinux's vesamenu.c32 on Host OS" >&2
+    sed 's|^UI vesamenu.c32|#UI vesamenu.c32|g' /tmp/usb_install/syslinux.cfg
+  fi
+
+  if [ -f /usr/lib/syslinux/libcom32.c32 ]; then
+    cp /usr/lib/syslinux/libcom32.c32 /tmp/usb_install
+  elif [ -f /usr/share/syslinux/libcom32.c32 ]; then
+    cp /usr/share/syslinux/libcom32.c32 /tmp/usb_install
+  fi
+
+  if [ -f /usr/lib/syslinux/libutil.c32 ]; then
+    cp /usr/lib/syslinux/libutil.c32 /tmp/usb_install
+  elif [ -f /usr/share/syslinux/libutil.c32 ]; then
+    cp /usr/share/syslinux/libutil.c32 /tmp/usb_install
+  fi
 
 # sync disk
   echo "syncing disk..."
