Disable arm arch for L4T

diff --git a/projects/Switch/devices/L4T/options b/projects/Switch/devices/L4T/options
--- a/projects/Switch/devices/L4T/options
+++ b/projects/Switch/devices/L4T/options
@@ -1,3 +1,9 @@
 #we use mesa for includes and headers, but replace the binaries by the nvidia blobs
 OPENGL="mesa"
 VULKAN="mesa"
+
+#disable arm target
+if [ "$ARCH" == "arm" ]; then
+    echo "Error: 32bit ARM arch is not supported by L4T"
+    exit 1
+fi
