update to libX11-20090717

diff --git a/packages/x11/lib/libX11/patches/20_libX11_remove-xdmcp.diff b/packages/x11/lib/libX11/patches/20_libX11_remove-xdmcp.diff
--- a/packages/x11/lib/libX11/patches/20_libX11_remove-xdmcp.diff
+++ b/packages/x11/lib/libX11/patches/20_libX11_remove-xdmcp.diff
@@ -1,7 +1,7 @@
-diff -Naur libX11-1.2.1.orig/configure libX11-1.2.1/configure
---- libX11-1.2.1.orig/configure	2009-04-08 19:00:52.000000000 +0200
-+++ libX11-1.2.1/configure	2009-04-08 23:31:35.000000000 +0200
-@@ -20784,90 +20784,10 @@
+diff -Naur libX11-1.2.2.orig/configure libX11-1.2.2/configure
+--- libX11-1.2.2.orig/configure	2009-07-10 17:23:15.000000000 +0200
++++ libX11-1.2.2/configure	2009-07-10 17:30:00.000000000 +0200
+@@ -13006,116 +13006,10 @@
  case "$ac_cv_use_xcb" in
  no)
  	X11_REQUIRES="xau xcmiscproto bigreqsproto"
@@ -9,93 +9,119 @@ diff -Naur libX11-1.2.1.orig/configure libX11-1.2.1/configure
 +	X11_EXTRA_DEPS="xau"
  
  pkg_failed=no
--{ echo "$as_me:$LINENO: checking for XDMCP" >&5
--echo $ECHO_N "checking for XDMCP... $ECHO_C" >&6; }
+-{ $as_echo "$as_me:$LINENO: checking for XDMCP" >&5
+-$as_echo_n "checking for XDMCP... " >&6; }
  
--if test -n "$PKG_CONFIG"; then
--        if test -n "$PKG_CONFIG" && \
--    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xdmcp\"") >&5
+-if test -n "$XDMCP_CFLAGS"; then
+-    pkg_cv_XDMCP_CFLAGS="$XDMCP_CFLAGS"
+- elif test -n "$PKG_CONFIG"; then
+-    if test -n "$PKG_CONFIG" && \
+-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xdmcp\"") >&5
 -  ($PKG_CONFIG --exists --print-errors "xdmcp") 2>&5
 -  ac_status=$?
--  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
 -  (exit $ac_status); }; then
 -  pkg_cv_XDMCP_CFLAGS=`$PKG_CONFIG --cflags "xdmcp" 2>/dev/null`
 -else
 -  pkg_failed=yes
 -fi
--else
--	pkg_failed=untried
+- else
+-    pkg_failed=untried
 -fi
--if test -n "$PKG_CONFIG"; then
--        if test -n "$PKG_CONFIG" && \
--    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xdmcp\"") >&5
+-if test -n "$XDMCP_LIBS"; then
+-    pkg_cv_XDMCP_LIBS="$XDMCP_LIBS"
+- elif test -n "$PKG_CONFIG"; then
+-    if test -n "$PKG_CONFIG" && \
+-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xdmcp\"") >&5
 -  ($PKG_CONFIG --exists --print-errors "xdmcp") 2>&5
 -  ac_status=$?
--  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
 -  (exit $ac_status); }; then
 -  pkg_cv_XDMCP_LIBS=`$PKG_CONFIG --libs "xdmcp" 2>/dev/null`
 -else
 -  pkg_failed=yes
 -fi
--else
--	pkg_failed=untried
+- else
+-    pkg_failed=untried
 -fi
 -
+-
+-
 -if test $pkg_failed = yes; then
--	XDMCP_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xdmcp"`
+-
+-if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+-        _pkg_short_errors_supported=yes
+-else
+-        _pkg_short_errors_supported=no
+-fi
+-        if test $_pkg_short_errors_supported = yes; then
+-	        XDMCP_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "xdmcp" 2>&1`
+-        else
+-	        XDMCP_PKG_ERRORS=`$PKG_CONFIG --print-errors "xdmcp" 2>&1`
+-        fi
 -	# Put the nasty error message in config.log where it belongs
--	echo "$XDMCP_PKG_ERRORS" 1>&5
+-	echo "$XDMCP_PKG_ERRORS" >&5
 -
--	{ { echo "$as_me:$LINENO: error: Package requirements (xdmcp) were not met.
+-	{ { $as_echo "$as_me:$LINENO: error: Package requirements (xdmcp) were not met:
+-
+-$XDMCP_PKG_ERRORS
+-
 -Consider adjusting the PKG_CONFIG_PATH environment variable if you
 -installed software in a non-standard prefix.
 -
--Alternatively you may set the XDMCP_CFLAGS and XDMCP_LIBS environment variables
--to avoid the need to call pkg-config.  See the pkg-config man page for
--more details." >&5
--echo "$as_me: error: Package requirements (xdmcp) were not met.
+-Alternatively, you may set the environment variables XDMCP_CFLAGS
+-and XDMCP_LIBS to avoid the need to call pkg-config.
+-See the pkg-config man page for more details.
+-" >&5
+-$as_echo "$as_me: error: Package requirements (xdmcp) were not met:
+-
+-$XDMCP_PKG_ERRORS
+-
 -Consider adjusting the PKG_CONFIG_PATH environment variable if you
 -installed software in a non-standard prefix.
 -
--Alternatively you may set the XDMCP_CFLAGS and XDMCP_LIBS environment variables
--to avoid the need to call pkg-config.  See the pkg-config man page for
--more details." >&2;}
+-Alternatively, you may set the environment variables XDMCP_CFLAGS
+-and XDMCP_LIBS to avoid the need to call pkg-config.
+-See the pkg-config man page for more details.
+-" >&2;}
 -   { (exit 1); exit 1; }; }
 -elif test $pkg_failed = untried; then
--	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+-	{ { $as_echo "$as_me:$LINENO: error: in \`$ac_pwd':" >&5
+-$as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
+-{ { $as_echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 -is in your PATH or set the PKG_CONFIG environment variable to the full
 -path to pkg-config.
 -
--Alternatively you may set the XDMCP_CFLAGS and XDMCP_LIBS environment variables
--to avoid the need to call pkg-config.  See the pkg-config man page for
--more details.
+-Alternatively, you may set the environment variables XDMCP_CFLAGS
+-and XDMCP_LIBS to avoid the need to call pkg-config.
+-See the pkg-config man page for more details.
 -
--To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
+-To get pkg-config, see <http://pkg-config.freedesktop.org/>.
 -See \`config.log' for more details." >&5
--echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+-$as_echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
 -is in your PATH or set the PKG_CONFIG environment variable to the full
 -path to pkg-config.
 -
--Alternatively you may set the XDMCP_CFLAGS and XDMCP_LIBS environment variables
--to avoid the need to call pkg-config.  See the pkg-config man page for
--more details.
+-Alternatively, you may set the environment variables XDMCP_CFLAGS
+-and XDMCP_LIBS to avoid the need to call pkg-config.
+-See the pkg-config man page for more details.
 -
--To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
+-To get pkg-config, see <http://pkg-config.freedesktop.org/>.
 -See \`config.log' for more details." >&2;}
--   { (exit 1); exit 1; }; }
+-   { (exit 1); exit 1; }; }; }
 -else
 -	XDMCP_CFLAGS=$pkg_cv_XDMCP_CFLAGS
 -	XDMCP_LIBS=$pkg_cv_XDMCP_LIBS
--        { echo "$as_me:$LINENO: result: yes" >&5
--echo "${ECHO_T}yes" >&6; }
+-        { $as_echo "$as_me:$LINENO: result: yes" >&5
+-$as_echo "yes" >&6; }
 -	:
 -fi
- 	{ echo "$as_me:$LINENO: checking for XdmcpWrap in -lXdmcp" >&5
- echo $ECHO_N "checking for XdmcpWrap in -lXdmcp... $ECHO_C" >&6; }
+ 	{ $as_echo "$as_me:$LINENO: checking for XdmcpWrap in -lXdmcp" >&5
+ $as_echo_n "checking for XdmcpWrap in -lXdmcp... " >&6; }
  if test "${ac_cv_lib_Xdmcp_XdmcpWrap+set}" = set; then
-diff -Naur libX11-1.2.1.orig/src/ConnDis.c libX11-1.2.1/src/ConnDis.c
---- libX11-1.2.1.orig/src/ConnDis.c	2009-04-08 19:00:52.000000000 +0200
-+++ libX11-1.2.1/src/ConnDis.c	2009-04-08 23:32:30.000000000 +0200
+diff -Naur libX11-1.2.2.orig/src/ConnDis.c libX11-1.2.2/src/ConnDis.c
+--- libX11-1.2.2.orig/src/ConnDis.c	2009-07-10 17:23:15.000000000 +0200
++++ libX11-1.2.2/src/ConnDis.c	2009-07-10 17:30:25.000000000 +0200
 @@ -39,7 +39,9 @@
  #include <X11/Xlibint.h>
  #include <X11/Xtrans/Xtrans.h>
@@ -106,28 +132,3 @@ diff -Naur libX11-1.2.1.orig/src/ConnDis.c libX11-1.2.1/src/ConnDis.c
  #include <stdio.h>
  #include <ctype.h>
  #include <unistd.h>
-diff -Naur libX11-1.2.1/configure.ac libX11-1.2.1.patch/configure.ac
---- libX11-1.2.1/configure.ac	2009-04-08 00:18:30.000000000 +0200
-+++ libX11-1.2.1.patch/configure.ac	2009-04-09 02:19:55.224211885 +0200
-@@ -49,9 +49,18 @@
- case "$ac_cv_use_xcb" in
- no)
- 	X11_REQUIRES="xau xcmiscproto bigreqsproto"
--	X11_EXTRA_DEPS="xau xdmcp"
--	PKG_CHECK_MODULES(XDMCP, xdmcp)
--	AC_CHECK_LIB(Xdmcp, XdmcpWrap, [xdmauth="yes"], [xdmauth="no"], [$XDMCP_LIBS])
-+	X11_EXTRA_DEPS="xau"
-+	PKG_CHECK_MODULES(XDMCP, xdmcp,
-+		AC_CHECK_LIB(Xdmcp, XdmcpWrap,
-+			[
-+	        	AC_CHECK_LIB(Xdmcp, XdmcpWrap, [xdmauth="yes"], [xdmauth="no"], [$XDMCP_LIBS])
-+	        	X11_EXTRA_DEPS="$X11_EXTRA_DEPS xdmcp"
-+			],
-+			[
-+			XDMCP_CFLAGS=
-+			XDMCP_LIBS=
-+			], [$XDMCP_LIBS]),
-+		[AC_MSG_RESULT(no)])
- 	AC_DEFINE(USE_XCB, 0, [Use XCB for low-level protocol implementation])
- 	;;
- *)
