busybox-initramfs: simplyfing fsck command, cleanups
Signed-off-by: Stephan Raue <stephan@openelec.tv>

diff --git a/packages/initramfs/sysutils/busybox-initramfs/scripts/init b/packages/initramfs/sysutils/busybox-initramfs/scripts/init
--- a/packages/initramfs/sysutils/busybox-initramfs/scripts/init
+++ b/packages/initramfs/sysutils/busybox-initramfs/scripts/init
@@ -94,19 +94,17 @@ REBOOT="0"
   }
 
   mount_part() {
-    progress "trying to mount $1 ..."
+    progress "check filesystem $1 ..."
+      /sbin/fsck -M -T -a $1 > /dev/null 2>&1
 
-      progress "check filesystem $1 ..."
-        /sbin/fsck -M -V -a -t !ntfs,!xfs,!vfat $1 > /dev/null 2>&1
-
-      for i in 1 2 3 4 5 6 7 8 9 10; do
-        ERR_ENV=1
-        progress "mount filesystem $1 ..."
-        /bin/busybox mount -o $3 $1 $2 > /dev/null 2>&1
-        [ "$?" -eq "0" ] && ERR_ENV=0 && break
-        /bin/busybox usleep 1000000
-      done
-      [ "$ERR_ENV" -ne "0" ] && error "INIT_4" "Could not mount $1" && debug_shell
+    for i in 1 2 3 4 5 6 7 8 9 10; do
+      ERR_ENV=1
+      progress "mount filesystem $1 ..."
+      /bin/busybox mount -o $3 $1 $2 > /dev/null 2>&1
+      [ "$?" -eq "0" ] && ERR_ENV=0 && break
+      /bin/busybox usleep 1000000
+    done
+    [ "$ERR_ENV" -ne "0" ] && error "INIT_4" "Could not mount $1" && debug_shell
   }
 
   update() {
