add ati and intel (doesn't build) graphic driver, create a project dir with various kernel config, diskimages now in target/

diff --git a/packages/x11/driver/xf86-video-ati/patches/10_cross-compile.diff b/packages/x11/driver/xf86-video-ati/patches/10_cross-compile.diff
--- a/packages/x11/driver/xf86-video-ati/patches/10_cross-compile.diff
+++ b/packages/x11/driver/xf86-video-ati/patches/10_cross-compile.diff
@@ -1,7 +1,6 @@
-diff -Naur xf86-video-openchrome-0.2.903.orig/configure xf86-video-openchrome-0.2.903/configure
---- xf86-video-openchrome-0.2.903.orig/configure	2008-08-30 17:34:34.000000000 +0200
-+++ xf86-video-openchrome-0.2.903/configure	2008-08-30 17:34:50.000000000 +0200
-@@ -21163,7 +21163,7 @@
+--- xf86-video-ati-6.10.0.orig/configure	2009-01-09 18:46:01.000000000 +0100
++++ xf86-video-ati-6.10.0/configure	2009-01-09 18:46:45.000000000 +0100
+@@ -21389,7 +21389,7 @@
  if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
@@ -10,7 +9,7 @@ diff -Naur xf86-video-openchrome-0.2.903.orig/configure xf86-video-openchrome-0.
    { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
  echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
     { (exit 1); exit 1; }; }
-@@ -21188,7 +21188,7 @@
+@@ -21414,7 +21414,7 @@
  if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
@@ -19,7 +18,7 @@ diff -Naur xf86-video-openchrome-0.2.903.orig/configure xf86-video-openchrome-0.
    { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
  echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
     { (exit 1); exit 1; }; }
-@@ -21213,7 +21213,7 @@
+@@ -21439,7 +21439,7 @@
  if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
@@ -28,7 +27,16 @@ diff -Naur xf86-video-openchrome-0.2.903.orig/configure xf86-video-openchrome-0.
    { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
  echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
     { (exit 1); exit 1; }; }
-@@ -21563,7 +21563,7 @@
+@@ -21464,7 +21464,7 @@
+ if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+-  test "$cross_compiling" = yes &&
++  test "$cross_compiling" = dummy &&
+   { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+ echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+    { (exit 1); exit 1; }; }
+@@ -23059,7 +23059,7 @@
  if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
