config/functions: add function install_driver_addon_files

diff --git a/config/functions b/config/functions
--- a/config/functions
+++ b/config/functions
@@ -344,6 +344,25 @@ done
        -i "$addon_xml"
 }
 
+install_driver_addon_files() {
+  if [ "$#" -eq 0 ] ; then
+    printf "$(print_color CLR_ERROR "no module search path defined")\n"
+    exit 1
+  fi
+
+  PKG_MODULE_DIR="$INSTALL/$(get_full_module_dir $PKG_ADDON_ID)/updates/$PKG_ADDON_ID"
+  PKG_ADDON_DIR="$INSTALL/usr/share/$MEDIACENTER/addons/$PKG_ADDON_ID"
+
+  mkdir -p $PKG_MODULE_DIR
+  find $@ -name \*.ko -exec cp {} $PKG_MODULE_DIR \;
+
+  find $PKG_MODULE_DIR -name \*.ko -exec $STRIP --strip-debug {} \;
+
+  mkdir -p $PKG_ADDON_DIR
+  cp $PKG_DIR/changelog.txt $PKG_ADDON_DIR
+  install_addon_files "$PKG_ADDON_DIR"
+}
+
 install_addon_files() {
   install_addon_source "$1"
   install_addon_images "$1"
