config/version: move to distro
The information within config/version contains information that is about
LibreELEC the distribution, so place it there. Config/version should contain
version information about the LibreELEC the buildsystem.

Signed-off-by: Ian Leonard <antonlacon@gmail.com>

diff --git a/config/options b/config/options
--- a/config/options
+++ b/config/options
@@ -25,13 +25,8 @@ TARGET_ARCH="${ARCH}"
 # include helper functions
 . config/functions
 
-# include versioning
-. config/version
-
-# read DISTRO versioning if available
-if [ -f "${DISTRO_DIR}/${DISTRO}/version" ]; then
-  . "${DISTRO_DIR}/${DISTRO}/version"
-fi
+# read DISTRO version information
+. "${DISTRO_DIR}/${DISTRO}/version" || die "\nERROR: No distro version present\n"
 
 # read DISTRO options if available
 if [ -f "${DISTRO_DIR}/${DISTRO}/options" ]; then
