config/release: add MD5 check to 'create_installstick'
Signed-off-by: Stephan Raue <stephan@openelec.tv>

diff --git a/config/release/create_installstick b/config/release/create_installstick
--- a/config/release/create_installstick
+++ b/config/release/create_installstick
@@ -56,6 +56,25 @@ echo "# Please read the instructions and use very carefully.. #"
 echo "#                                                       #"
 echo "#########################################################"
 
+# check MD5 sums
+  echo "checking MD5 sum..."
+  md5sum -c target/KERNEL.md5
+  MD5_ERROR=$?
+  md5sum -c target/SYSTEM.md5
+  MD5_ERROR=$?
+
+if [ $MD5_ERROR = 1 ]; then
+  echo "#########################################################"
+  echo "#                                                       #"
+  echo "# OpenELEC.tv failed md5 check - Installation will quit #"
+  echo "#                                                       #"
+  echo "#      Your original download was probably corrupt.     #"
+  echo "#   Please visit www.openelec.tv and get another copy   #"
+  echo "#                                                       #"
+  echo "#########################################################"
+  exit 1
+fi
+
 # (TODO) umount anything
   umount $PART
 
