busybox-initramfs: quote tests and some more variables
Signed-off-by: Stephan Raue <stephan@openelec.tv>

diff --git a/packages/sysutils/busybox-initramfs/scripts/init b/packages/sysutils/busybox-initramfs/scripts/init
--- a/packages/sysutils/busybox-initramfs/scripts/init
+++ b/packages/sysutils/busybox-initramfs/scripts/init
@@ -4,7 +4,7 @@ UPDATE_DIR=/storage/.update
 
 IMAGE_SYSTEM="SYSTEM"
 IMAGE_KERNEL="KERNEL"
-REBOOT=0
+REBOOT="0"
 
 # mount all needed special filesystems
   /bin/busybox mount -t devtmpfs none /dev
@@ -31,18 +31,18 @@ REBOOT=0
     esac
   done
 
-  if test "$FASTBOOT" = yes; then
+  if test "$FASTBOOT" = "yes"; then
     IONICE="/bin/busybox ionice -c 1 -n 0"
   fi
 
   progress() {
-    if test "$DEBUG" = yes; then
+    if test "$DEBUG" = "yes"; then
       echo "### $1 ###"
     fi
   }
 
   show_splash() {
-    if [ "$SPLASH" = no ]; then
+    if [ "$SPLASH" = "no" ]; then
       break
     else
       if [ -f "/bin/ply-image" -a -f "/splash.png" ]; then
@@ -65,10 +65,10 @@ REBOOT=0
     for i in 1 2 3 4 5 6 7 8 9 10; do
       ERR_ENV=1
       $IONICE /bin/busybox mount -o $3 $1 $2 > /dev/null 2>&1
-      [ $? -eq 0 ] && ERR_ENV=0 && break
+      [ "$?" -eq "0" ] && ERR_ENV=0 && break
       /bin/busybox usleep 1000000
     done
-    [ $ERR_ENV -ne 0 ] && error "INIT_4" "Could not mount $1" && debug_shell
+    [ "$ERR_ENV" -ne "0" ] && error "INIT_4" "Could not mount $1" && debug_shell
   }
 
   update() {
@@ -78,7 +78,7 @@ REBOOT=0
         $IONICE /bin/busybox mv $UPDATE_DIR/$2 $3
         $IONICE /bin/busybox mount -o remount,ro /flash
         $IONICE /bin/busybox sync
-        [ $2 = $IMAGE_KERNEL ] && REBOOT=1
+        [ "$2" = "$IMAGE_KERNEL" ] && REBOOT="1"
     fi
   }
 
@@ -91,7 +91,7 @@ REBOOT=0
     update "Kernel" "$IMAGE_KERNEL" "/flash/$IMAGE_KERNEL"
     update "System" "$IMAGE_SYSTEM" "/flash/$IMAGE_SYSTEM"
 
-    if test "$REBOOT" -eq 1; then
+    if test "$REBOOT" -eq "1"; then
       echo "System reboots now..." && \
       /bin/busybox reboot
     fi
@@ -99,7 +99,7 @@ REBOOT=0
 
   if [ -f "/flash/$IMAGE_SYSTEM" ]; then
     mount_part "/flash/$IMAGE_SYSTEM" "/sysroot" "ro,loop"
-    [ $ERR_ENV -ne 0 ] && debug_shell
+    [ "$ERR_ENV" -ne "0" ] && debug_shell
   else
     error "INIT_2" "Could not find system."
     debug_shell
