busybox: move systemd to /usr/lib
Signed-off-by: Stephan Raue <stephan@openelec.tv>

diff --git a/packages/sysutils/busybox/scripts/init b/packages/sysutils/busybox/scripts/init
--- a/packages/sysutils/busybox/scripts/init
+++ b/packages/sysutils/busybox/scripts/init
@@ -570,7 +570,7 @@
       mount --move /storage /sysroot/storage
     fi
 
-    [ -f "/sysroot/lib/systemd/systemd" ] || error "final_check" "Could not find system."
+    [ -f "/sysroot/usr/lib/systemd/systemd" ] || error "final_check" "Could not find system."
   }
 
   if [ "${boot%%=*}" = "FILE" ]; then
@@ -606,6 +606,6 @@
     echo "" > /sysroot/dev/.storage_netboot
   fi
   # switch to new sysroot and start real init
-  exec /bin/busybox switch_root /sysroot /lib/systemd/systemd $INIT_ARGS
+  exec /bin/busybox switch_root /sysroot /usr/lib/systemd/systemd $INIT_ARGS
 
   error "switch_root" "Error in initramfs. Could not switch to new root"
