scripts: minor cosmetics

diff --git a/scripts/autoreconf b/scripts/autoreconf
--- a/scripts/autoreconf
+++ b/scripts/autoreconf
@@ -20,7 +20,11 @@
 
 . config/options $1
 
-[ ! -f "$PKG_BUILD/configure.in" -a ! -f "$PKG_BUILD/configure.ac" ] && echo "configure.in or configure.ac not found" && exit 1
+if [ ! -f "$PKG_BUILD/configure.in" \
+    -a ! -f "$PKG_BUILD/configure.ac" ] ; then
+  echo "configure.in or configure.ac not found"
+  exit 1
+fi
 
 if [ ! -f $PKG_BUILD/.autoreconf-done ] ; then
   touch $PKG_BUILD/NEWS $PKG_BUILD/AUTHORS $PKG_BUILD/ChangeLog
@@ -32,5 +36,3 @@ if [ ! -f $PKG_BUILD/.autoreconf-done ] ; then
   do_autoreconf $PKG_BUILD
   touch $PKG_BUILD/.autoreconf-done
 fi
-
-exit 0
