create_addon: do not write usage on non-matching addon-pattern

diff --git a/scripts/create_addon b/scripts/create_addon
--- a/scripts/create_addon
+++ b/scripts/create_addon
@@ -76,8 +76,9 @@ function find_addons() {
 
   local _count=$(wc -w <<< $_addons)
   if [ "$_count" == 0 ]; then
-    printf  "$(print_color CLR_ERROR "ERROR: '$1' matches nothing...")\n\n" ' '>&$SILENT_OUT
-    usage 1
+    printf  "$(print_color CLR_ERROR "ERROR: '$1' matches nothing...")\n" ' '>&$SILENT_OUT
+    printf  "for more informations type: ./scripts/create_addon --help\n" ' '>&$SILENT_OUT
+    exit 1
   fi
 
   echo $_addons
