scripts/create_addon_mt: support building/installing addons with a single plan

diff --git a/scripts/image_mt b/scripts/image_mt
--- a/scripts/image_mt
+++ b/scripts/image_mt
@@ -93,7 +93,7 @@ for directory in etc dev proc run sys tmp usr var flash storage; do
 done
 
 # Build image contents
-start_multithread_build image || die "Parallel build failure - see log for details. Time of failure: $(date)"
+MTADDONBUILD=no start_multithread_build image || die "Parallel build failure - see log for details. Time of failure: $(date)"
 
 echo "Successful build, creating image..." >&2
 
