scripts/install: exit if $INSTALL not set

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -30,6 +30,10 @@ if [ -z "$1" ]; then
   exit 1
 fi
 
+if [ -z "$INSTALL" ] ; then
+  echo "error: '\$INSTALL' not set! this script is not intended to be run manually"
+  exit 1
+fi
 mkdir -p $STAMPS_INSTALL/$1
 
 if [ -f $STAMP -a $PKG_DIR/install -nt $STAMP ]; then
